#! /bin/bash
SCRIPT_DIR=$(dirname "$0")
INSTALL_DIR=$(realpath "$SCRIPT_DIR")
DOT_CONFIG="etc"

echo "Installing & linking .local to $INSTALL_DIR"
if [ ! -d "$HOME/.local" ]; then
    ln -s "$INSTALL_DIR" "$HOME/.local"
else
    echo "Directory $HOME/.local already exists!"
    exit
fi

if [ ! -d "$HOME/.config" ]; then
    ln -s "$INSTALL_DIR/$DOT_CONFIG" "$HOME/.config"
else
    echo "Directory $HOME/.config already exists!"
fi
